# Generated by Django 3.2.4 on 2021-07-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre del registro')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del colaborador')),
                ('foto', models.CharField(max_length=1, verbose_name='Fotografía que lo identifique')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefóno')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('pais', models.CharField(max_length=15, verbose_name='País')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.categoria')),
            ],
        ),
    ]
